version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4040:4040
    command: 'npm run start:dev'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: alsyed
      POSTGRES_PASSWORD: alsyed123
      POSTGRES_DB: alsyed
    ports:
      - 5432:5432
volumes:
  db_data:
